[package]

name = "timely"
version = "0.5.0"
authors = ["Frank McSherry <fmcsherry@me.com>"]

description = "A low-latency data-parallel dataflow system in Rust"

# These URLs point to more information about the repository
documentation = "https://frankmcsherry.github.com/timely-dataflow"
homepage = "https://github.com/frankmcsherry/timely-dataflow"
repository = "https://github.com/frankmcsherry/timely-dataflow.git"
keywords = ["timely", "dataflow"]
license = "MIT"

#build = "booktests.rs"

[http]
proxy = "http://proxy.cse.cuhk.edu.hk:8000"

[https]
proxy = "https://proxy.cse.cuhk.edu.hk:8000"

[features]
default=[]
logging=[]

[dependencies]
abomonation = "0.5"
abomonation_derive = "0.3"
timely_communication = "0.5"
byteorder="0.4.2"
time="0.1.34"
hostname = "^0.1"

[dev-dependencies]
timely_sort="0.1.6"
getopts="0.2.14"
rand="0.3.13"
#skeptic = "0.12"

#[build-dependencies]
#skeptic = "0.12"

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = false
